<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*ipythonrc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~I</string>
	<key>name</key>
	<string>ipythonrc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ipython-config</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>may not appear part way through a line</string>
			<key>match</key>
			<string>^\s*(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.ipython-config</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ipython-config</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>may not appear part way through a line. hilights the entire line if there is a problem</string>
			<key>match</key>
			<string>^.*\w+\s*(#).*$\n?</string>
			<key>name</key>
			<string>invalid.illegal.comment.number-sign.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(autocall|autoedit_syntax|autoindent|automagic|classic|color_info|confirm_exit|deep_reload|editor|include|log|logfile|banner|messages|nosep|pdb|pprint|pylab_import_all|quick|readline|wildcards_case_sensitive|object_info_string_level|multi_line_specials|system_verbose|wxversion|)\b</string>
			<key>name</key>
			<string>keyword.config.boolean.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(cache_size|screen_length)\b</string>
			<key>name</key>
			<string>keyword.config.numeric.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(colors|prompt_in1|prompt_in2|prompt_out|prompts_pad_left|separate_in|separate_out|separate_out2|xmode|system_header)\b</string>
			<key>name</key>
			<string>keyword.config.string.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(readline_parse_and_bind|readline_remove_delims|readline_merge_completions|readline_omit__names)\b</string>
			<key>name</key>
			<string>keyword.config.readline.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import_mod|import_some|import_all)\b</string>
			<key>name</key>
			<string>keyword.config.import.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(execute)\b</string>
			<key>name</key>
			<string>keyword.config.execute.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(execfile)\b</string>
			<key>name</key>
			<string>keyword.config.execute-file.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(alias)\b</string>
			<key>name</key>
			<string>keyword.config.alias.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Plain|Context|Verbose)\b</string>
			<key>name</key>
			<string>constant.exception-mode.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Linux|LightBG|NoColor)\b</string>
			<key>name</key>
			<string>constant.color-scheme.ipython-config</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(complete|menu-complete)\b</string>
			<key>name</key>
			<string>constant.completion-mode.readline.ipython-config</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>likely (very) imcomplete, just copied from example config</string>
			<key>match</key>
			<string>\b(possible-completions|tab-insert|reverse-search-history|forward-search-history|history-search-forward|history-search-backward|kill-line|unix-line-discard)\b</string>
			<key>name</key>
			<string>constant.bindings.readline.ipython-config</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ipython-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ipython-config</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.ipython-config</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ipython-config</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ipython-config</string>
	<key>uuid</key>
	<string>59D7CA34-7681-43E5-8964-53F132110218</string>
</dict>
</plist>
